apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-test
spec:
  workspaces:
    - name: source
  steps:
    - name: npm-install-test
      image: node:14
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-test
spec:
  workspaces:
    - name: source
  steps:
    - name: run-jasmine-tests
      image: node:14
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        npx jasmine
